language: node_js

node_js:
  - node
  - "8"
  - "10"

os:
  - osx
  - windows
  - linux

notifications:
  email:
    on_failure: always
    on_success: never

cache:
  directories:
    - node_modules

install:
  - npm install
  - npm install -g

script:
  - npm run lint
  - npm run test:report
